-LRB- CNN -RRB- -- Listed below are complete squad lists for the 16 finalists at Euro 2008 .

Champions Greece are aiming to defend their European crown .

Austria :

Goalkeepers : Juergen Macho -LRB- AEK Athens -RRB- , Alexander Manninger -LRB- Siena -RRB- , Ramazan Ozcan -LRB- Hoffenheim -RRB- . Defenders : Gyorgy Garics -LRB- Napoli -RRB- , Ronald Gercaliu -LRB- Austria Vienna -RRB- , Martin Hiden -LRB- Austria Carinthia -RRB- , Markus Katzer -LRB- Rapid Vienna -RRB- , Jurgen Patocka -LRB- Rapid Vienna -RRB- , Emanuel Pogatetz -LRB- Middlesbrough -RRB- , Sebastian Proedl -LRB- Sturm Graz -RRB- , Martin Stranzl -LRB- Spartak Moscow -RRB- . Midfielders : Rene Aufhauser -LRB- Salzburg -RRB- , Christian Fuchs -LRB- Mattersburg -RRB- , Andreas Ivanschitz -LRB- Panathinaikos -RRB- , Umit Korkmaz -LRB- Rapid Vienna -RRB- , Christoph Leitgeb -LRB- Salzburg -RRB- , Juergen Saeumel -LRB- Sturm Graz -RRB- , Joachim Standfest -LRB- Austria Vienna -RRB- , Ivica Vastic -LRB- Linz -RRB- . Strikers : Martin Harnik -LRB- Werder Bremen -RRB- , Erwin Hoffer -LRB- Rapid Vienna -RRB- , Roman Kienast -LRB- Ham-Kam -RRB- , Roland Linz -LRB- Braga -RRB- .

Czech Republic :

Goalkeepers : Petr Cech -LRB- Chelsea -RRB- , Jaromir Blazek -LRB- Nuremberg -RRB- , Daniel Zitka -LRB- Anderlecht -RRB- . Defenders : Zdenek Grygera -LRB- Juventus -RRB- , Marek Jankulovski -LRB- AC Milan -RRB- , Michal Kadlec -LRB- Sparta Prague -RRB- , Radoslav Kovac -LRB- Spartak Moscow -RRB- , Zdenek Pospech -LRB- Copenhagen -RRB- , David Rozehnal -LRB- Lazio -RRB- , Tomas Sivok -LRB- Sparta Prague -RRB- , Tomas Ujfalusi -LRB- Fiorentina -RRB- . Midfielders : Tomas Galasek -LRB- Nuremberg -RRB- , David Jarolim -LRB- Hamburg -RRB- , Marek Matejovsky -LRB- Reading -RRB- , Jaroslav Plasil -LRB- Osasuna -RRB- , Jan Polak -LRB- Anderlecht -RRB- , Daniel Pudil -LRB- Slavia Prague -RRB- , Libor Sionko -LRB- Copenhagen -RRB- , Stanislav Vlcek -LRB- Anderlecht -RRB- . Strikers : Milan Baros -LRB- Portsmouth -RRB- , Jan Koller -LRB- Nuremberg -RRB- , Martin Fenin -LRB- Eintracht Frankfurt -RRB- , Vaclav Sverkos -LRB- Banik Ostrava -RRB- .

Croatia :

Goalkeepers : Stipe Pletikosa -LRB- Spartak Moscow -RRB- , Vedran Runje -LRB- Lens -RRB- , Mario Galinovic -LRB- Panathinaikos -RRB- . Defenders : Vedran Corluka -LRB- Manchester City -RRB- , Dario Simic -LRB- AC Milan -RRB- , Robert Kovac -LRB- Borussia Dortmund -RRB- , Josip Simunic -LRB- Hertha Berlin -RRB- , Dario Knezevic -LRB- Livorno -RRB- , Hrvoje Vejic -LRB- Tomsk -RRB- , Danijel Pranjic -LRB- Heerenveen -RRB- . Midfielders : Darijo Srna -LRB- Shakhtar Donetsk -RRB- , Niko Kovac -LRB- Red Bull Salzburg -RRB- , Luka Modric -LRB- Tottenham -RRB- , Niko Kranjcar -LRB- Portsmouth -RRB- , Jerko Leko -LRB- Monaco -RRB- , Ivan Rakitic -LRB- Schalke -RRB- , Ognjen Vukojevic -LRB- Dinamo Bucharest -RRB- , Nikola Pokrivac -LRB- Monaco -RRB- . Forwards : Mladen Petric -LRB- Borussia Dortmund -RRB- , Ivica Olic -LRB- Hamburg -RRB- , Ivan Klasnic -LRB- Werder Bremen -RRB- , Igor Budan -LRB- Parma -RRB- , Nikola Kalinic -LRB- Hajduk Split -RRB- .

France :

Goalkeepers : Gregory Coupet -LRB- Lyon -RRB- , Sebastien Frey -LRB- Fiorentina -RRB- , Steve Mandanda -LRB- Marseille -RRB- . Defenders : Eric Abidal -LRB- Barcelona -RRB- , Jean-Alain Boumsong -LRB- Lyon -RRB- , Francois Clerc -LRB- Lyon -RRB- , Patrice Evra -LRB- Manchester United -RRB- , William Gallas -LRB- Arsenal -RRB- , Willy Sagnol -LRB- Bayern Munich -RRB- , Sebastien Squillaci -LRB- Lyon -RRB- , Lilian Thuram -LRB- Barcelona -RRB- . Midfielders : Lassana Diarra -LRB- Portsmouth -RRB- , Claude Makelele -LRB- Chelsea -RRB- , Jeremy Toulalan -LRB- Lyon -RRB- , Patrick Vieira -LRB- Inter Milan -RRB- , Samir Nasri -LRB- Marseille -RRB- Franck Ribery -LRB- Bayern Munich -RRB- . Forwards : Nicolas Anelka -LRB- Chelsea -RRB- , Karim Benzema -LRB- Lyon -RRB- , Bafetimbi Gomis -LRB- Saint-Etienne -RRB- , Sidney Govou -LRB- Lyon -RRB- , Thierry Henry -LRB- Barcelona -RRB- , Florent Malouda -LRB- Chelsea -RRB- .

Germany :

Goalkeepers : Rene Adler -LRB- Bayer Leverkusen -RRB- , Robert Enke -LRB- Hannover -RRB- , Jens Lehmann -LRB- Arsenal -RRB- . Defenders : Arne Friedrich -LRB- Hertha Berlin -RRB- , Clemens Fritz -LRB- Werder Bremen -RRB- , Marcell Jansen -LRB- Bayern Munich -RRB- , Philipp Lahm -LRB- Bayern Munich -RRB- , Per Mertesacker -LRB- Werder Bremen -RRB- , Christoph Metzelder -LRB- Real Madrid -RRB- , Heiko Westermann -LRB- Schalke -RRB- . Midfielders : Michael Ballack -LRB- Chelsea -RRB- , Tim Borowski -LRB- Werder Bremen -RRB- , Torsten Frings -LRB- Werder Bremen -RRB- , Thomas Hitzlsperger -LRB- Stuttgart -RRB- , David Odonkor -LRB- Real Betis -RRB- , Simon Rolfes -LRB- Bayer Leverkusen -RRB- , Bastian Schweinsteiger -LRB- Bayern Munich -RRB- , Piotr Trochowski -LRB- Hamburg -RRB- . Forwards : Mario Gomez -LRB- Stuttgart -RRB- , Miroslav Klose -LRB- Bayern Munich -RRB- , Kevin Kuranyi -LRB- Schalke -RRB- , Oliver Neuville -LRB- Borussia Moenchengladbach -RRB- , Lukas Podolski -LRB- Bayern Munich -RRB- .

Greece :

Goalkeepers : Antonis Nikopolidis -LRB- Olympiakos -RRB- , Costas Chalkias -LRB- Aris -RRB- , Alexandros Tzorvas -LRB- OFI Crete -RRB- . Defenders : Paraskevas Antzas -LRB- Olympiakos -RRB- , Giourkas Seitaridis -LRB- Atletico Madrid -RRB- , Loukas Vyntra -LRB- Panathinaikos -RRB- , Vassilis Torossidis -LRB- Olympiakos -RRB- , Sotiris Kyrgiakos -LRB- Eintracht Frankfurt -RRB- , Christos Patsatzoglou -LRB- Olympiakos -RRB- , Traianos Dellas -LRB- AEK -RRB- , Yiannis Goumas -LRB- Panathinaikos -RRB- , Nikos Spiropoulos -LRB- Panathinaikos -RRB- . Midfielders : Costas Katsouranis -LRB- Benfica -RRB- , Angelos Basinas -LRB- Real Mallorca -RRB- , Giorgos Karagounis -LRB- Panathinaikos -RRB- , Stelios Giannakopoulos -LRB- Bolton -RRB- , Alexandros Tziolis -LRB- Panathinaikos -RRB- , Ioannis Amanatidis -LRB- Eintracht Frankfurt -RRB- . Forwards : Georgios Samaras -LRB- Celtic -RRB- , Dimitris Salpigidis -LRB- Panathinaikos -RRB- , Angelos Charisteas -LRB- Nuremburg -RRB- , Fanis Gekas -LRB- Bayer Leverkusen -RRB- , Nikos Lymberopoulos -LRB- AEK -RRB- .

Italy :

Goalkeepers : Marco Amelia -LRB- Livorno -RRB- , Gianluigi Buffon -LRB- Juventus -RRB- , Morgan De Sanctis -LRB- Sevilla -RRB- . Defenders : Fabio Cannavaro -LRB- Real Madrid -RRB- , Andrea Barzagli -LRB- Palermo -RRB- , Giorgio Chiellini -LRB- Juventus -RRB- , Fabio Grosso -LRB- Lyon -RRB- , Marco Materazzi -LRB- Inter Milan -RRB- , Christian Panucci -LRB- Roma -RRB- , Gianluca Zambrotta -LRB- Barcelona -RRB- . Midfielders : Massimo Ambrosini -LRB- AC Milan -RRB- , Alberto Aquilani -LRB- Roma , Mauro Camoranesi -LRB- Juventus -RRB- , Daniele De Rossi -LRB- Roma -RRB- , Gennaro Gattuso -LRB- AC Milan -RRB- , Simone Perrotta -LRB- Roma -RRB- , Andrea Pirlo -LRB- AC Milan -RRB- . Strikers : Marco Borriello -LRB- Genoa -RRB- , Antonio Cassano -LRB- Sampdoria -RRB- , Antonio Di Natale -LRB- Udinese -RRB- , Alessandro Del Piero -LRB- Juventus -RRB- , Fabio Quagliarella -LRB- Udinese -RRB- , Luca Toni -LRB- Bayern Munich -RRB-

Netherlands :

Goalkeepers : Edwin van der Sar -LRB- Manchester United -RRB- , Maarten Stekelenburg -LRB- Ajax -RRB- , Henk Timmer -LRB- Feyenoord -RRB- . Defenders : Wilfred Bouma -LRB- Aston Villa -RRB- , Tim de Cler -LRB- Feyenoord -RRB- , John Heitinga -LRB- Ajax -RRB- , Joris Mathijsen -LRB- Hamburg -RRB- , Mario Melchiot -LRB- Wigan Athletic -RRB- , Andre Ooijer -LRB- Blackburn Rovers -RRB- . Midfielders : Ibrahim Afellay -LRB- PSV Eindhoven -RRB- , Giovanni van Bronckhorst -LRB- Feyenoord -RRB- , Orlando Engelaar -LRB- FC Twente -RRB- , Nigel de Jong -LRB- Hamburg -RRB- , Wesley Sneijder -LRB- Real Madrid -RRB- , Rafael van der Vaart -LRB- Hamburg -RRB- , Demy de Zeeuw -LRB- AZ Alkmaar -RRB- . Forwards : Ryan Babel -LRB- Liverpool -RRB- , Klaas Jan Huntelaar -LRB- Ajax -RRB- , Dirk Kuyt -LRB- Liverpool -RRB- , Ruud van Nistelrooy -LRB- Real Madrid -RRB- , Robin van Persie -LRB- Arsenal -RRB- , Arjen Robben -LRB- Real Madrid -RRB- , Jan Vennegoor -LRB- Celtic -RRB- .

Poland :

Goalkeepers : Artur Boruc -LRB- Celtic -RRB- , Tomasz Kuszczak -LRB- Manchester United -RRB- , Lukasz Fabianski -LRB- Arsenal -RRB- . Defenders : Marcin Wasilewski -LRB- Anderlecht -RRB- , Pawel Golanski -LRB- Steaua Bucharest -RRB- , Mariusz Jop -LRB- FC Moscow -RRB- , Jacek Bak -LRB- Austria Vienna -RRB- , Michal Zewlakow -LRB- Olympiakos -RRB- , Adam Kokoszka -LRB- Wisla Krakow -RRB- , Jakub Wawrzyniak -LRB- Legia Warsaw -RRB- . Midfielders : Mariusz Lewandowski -LRB- Shakhtar Donetsk -RRB- , Dariusz Dudka -LRB- Wisla Krakow -RRB- , Jakub Blaszczykowski -LRB- Borussia Dortmund -RRB- , Rafal Murawski -LRB- Lech Poznan -RRB- , Michal Pazdan -LRB- Gornik Zabrze -RRB- , Lukasz Gargula -LRB- GKS Belchatow -RRB- , Jacek Krzynowek -LRB- VfL Wolfsburg -RRB- , Roger Guerreiro -LRB- Legia Warsaw -RRB- . Forwards : Maciej Zurawski -LRB- Larissa -RRB- , Euzebiusz Smolarek -LRB- Racing Santander -RRB- , Marek Saganowski -LRB- Southampton -RRB- , Tomasz Zahorski -LRB- Gornik Zabrze -RRB- , Wojciech Lobodzinski -LRB- Wisla Krakow -RRB- .

Portugal :

Goalkeepers : Ricardo -LRB- Real Betis -RRB- , Quim -LRB- Benfica -RRB- , Rui Patricio -LRB- Sporting Lisbon -RRB- . Defenders : Paulo Ferreira -LRB- Chelea -RRB- , Ricardo Carvalho -LRB- Chelsea -RRB- , Jose Bosingwa -LRB- Chelsea -RRB- , Bruno Alves -LRB- Porto -RRB- , Jorge Ribeiro -LRB- Boavista -RRB- , Miguel -LRB- Valencia -RRB- , Fernando Meira -LRB- Stuttgart -RRB- , Pepe -LRB- Real Madrid -RRB- . Midfielders : Petit -LRB- Benfica -RRB- , Deco -LRB- Barcelona -RRB- , Raul Meireles -LRB- Porto -RRB- , Miguel Veloso -LRB- Sporting Lisbon -RRB- , João Moutinho -LRB- Sporting Lisbon -RRB- , Nani -LRB- Manchester United -RRB- , Ricardo Quaresma -LRB- Porto -RRB- . Forwards : Nuno Gomes -LRB- Benfica -RRB- , Simão Sabrosa -LRB- Atletico Madrid -RRB- , Cristiano Ronaldo -LRB- Manchester United -RRB- , Hugo Almeida -LRB- Werder Bremen -RRB- , Helder Postiga -LRB- Panathinaikos -RRB- .

Romania :

Goalkeepers : Bogdan Lobont -LRB- Dinamo Bucharest -RRB- , Marius Popa -LRB- Poli Timisoara -RRB- , Eduard Stancioiu -LRB- CFR Cluj -RRB- . Defenders : Cosmin Contra -LRB- Getafe -RRB- , Gabriel Tamas -LRB- Auxerre -RRB- , Dorin Goian -LRB- Steaua Bucharest -RRB- , Cristian Chivu -LRB- Inter Milan -RRB- , Razvan Rat -LRB- Sakhtor Donetsk -RRB- , Sorin Ghionea -LRB- Steaua Bucharest -RRB- , Cristian Sapunaru -LRB- Rapid Bucharest -RRB- , Stefan Radu -LRB- Lazio -RRB- , Cosmin Moti -LRB- Dinamo Bucharest -RRB- . Midfielders : Florentin Petre -LRB- CSKA Sofia -RRB- , Razvan Cocis -LRB- Lokomotiv Moscow -RRB- , Mirel Radoi -LRB- Steaua Bucharest -RRB- , Nicolae Dica -LRB- Steaua Bucharest -RRB- , Paul Codrea -LRB- Sienna -RRB- , Banel Nicolita -LRB- Steaua Bucharest -RRB- , Adrian Cristea -LRB- Dinamo Bucharest -RRB- . Forwards : Adrian Mutu -LRB- Fiorentina -RRB- , Ciprian Marica -LRB- Stuttgart -RRB- , Daniel Niculae -LRB- Auxerre -RRB- , Marius Niculae -LRB- Inverness -RRB- .

Russia : Goalkeepers : Igor Akinfeyev -LRB- CSKA Moscow -RRB- , Vladimir Gabulov -LRB- Amkar Perm -RRB- , Vyacheslav Malafeyev -LRB- Zenit St Petersburg -RRB- . Defenders : Alexander Anyukov -LRB- Zenit St Petersburg -RRB- , Alexei Berezutsy , Vasily Berezursky , Sergei Ignashevich -LRB- all CSKA Moscow -RRB- , Denis Kolodin -LRB- Dynamo Moscow -RRB- , Renat Yanbayev -LRB- Lokomotiv Moscow -RRB- . Midfielders : Diniyar Bilyaletdinov , Dmitry Torbinsky -LRB- both Lokomotiv Moscow -RRB- , Vladimir Bystrov -LRB- Spartak Moscow -RRB- , Yury Zhirkov -LRB- CSKA Moscow -RRB- , Konstantin Zyryanov , Roman Shirokov -LRB- both Zenit St Petersburg -RRB- , Igor Semshov -LRB- Dynamo Moscow -RRB- , Sergei Semak -LRB- Kazan -RRB- . Strikers : Roman Adamov -LRB- FC Moscow -RRB- , Roman Pavlyuchenko -LRB- Spartak Moscow -RRB- , Pavel Pogrebnyak , Andrei Arshavin -LRB- both Zenit St Petersburg -RRB- , Dmitry Sychev -LRB- Lokomotiv Moscow -RRB- , Ivan Saenko -LRB- Nuremberg -RRB- .

Spain :

Goalkeepers : Iker Casillas -LRB- Real Madrid -RRB- , Pepe Reina -LRB- Liverpool -RRB- , Andres Palop -LRB- Sevilla -RRB- . Defenders : Sergio Ramos -LRB- Real Madrid -RRB- , Joan Capdevila -LRB- Villarreal -RRB- , Raul Albiol -LRB- Valencia -RRB- , Carles Puyol -LRB- Barcelona -RRB- , Carlos Marchena -LRB- Valencia -RRB- , Fernando Navarro -LRB- Real Mallorca -RRB- , Alvaro Arbeloa -LRB- Liverpool -RRB- , Juanito -LRB- Real Betis -RRB- . Midfielders : Cesc Fabregas -LRB- Arsenal -RRB- , Andres Iniesta -LRB- Barcelona -RRB- , Xavi -LRB- Barcelona -RRB- , David Silva -LRB- Valencia -RRB- , Santi Cazorla -LRB- Villarreal -RRB- , Xabi Alonso -LRB- Liverpool -RRB- , Ruben de la Red -LRB- Getafe -RRB- , Marcos Senna -LRB- Villarreal -RRB- . Forwards : David Villa -LRB- Valencia -RRB- , Daniel Guiza -LRB- Real Mallorca -RRB- , Sergio Garcia -LRB- Real Zaragoza -RRB- , Fernando Torres -LRB- Liverpool -RRB- .

Sweden :

Goalkeepers : Andreas Isaksson -LRB- Manchester City -RRB- , Rami Shaaban -LRB- Hammarby -RRB- , Johan Wiland -LRB- Elfsborg -RRB- . Defenders : Olof Mellberg -LRB- Aston Villa -RRB- , Petter Hansson -LRB- Rennes -RRB- , Mikael Nilsson -LRB- Panathinaikos -RRB- , Niclas Alexandersson -LRB- Gothenburg -RRB- , Andreas Granqvist -LRB- Helsingborg -RRB- , Daniel Majstorovic -LRB- Basel -RRB- , Fredrik Stoor -LRB- Rosenborg -RRB- , Mikael Dorsin -LRB- CFR Cluj -RRB- . Midfielders : Tobias Linderoth -LRB- Galatasaray -RRB- , Daniel Andersson -LRB- Malmo -RRB- , Anders Svensson -LRB- Elfsborg -RRB- , Kim Kallstrom -LRB- Lyon -RRB- , Christian Wilhelmsson -LRB- Deportivo La Coruna -RRB- , Fredrik Ljungberg -LRB- West Ham -RRB- , Sebastian Larsson -LRB- Birmingham City -RRB- . Forwards : Zlatan Ibrahimovic -LRB- Inter Milan -RRB- , Johan Elmander -LRB- Toulouse -RRB- , Marcus Allback -LRB- Copenhagen -RRB- , Markus Rosenberg -LRB- Werder Bremen -RRB- , Henrik Larsson -LRB- Helsingborg -RRB- .

Switzerland :

Goalkeepers : Diego Benaglio -LRB- Wolfsburg -RRB- , Eldin Jakupovic -LRB- Grasshopper -RRB- , Pascal Zuberbuehler -LRB- Xamax Neuchatel -RRB- . Defenders : Philipp Degen -LRB- Borussia Dortmund -RRB- , Johan Djourou -LRB- Arsenal -RRB- , Stephane Grichting -LRB- Auxerre -RRB- , Stephan Lichtsteiner -LRB- Lille -RRB- , Ludovic Magnin -LRB- Stuttgart -RRB- , Patrick Mueller -LRB- Lyon -RRB- , Philippe Senderos -LRB- Arsenal -RRB- , Christoph Spycher -LRB- Eintracht Frankfurt -RRB- . Midfielders : Tranquillo Barnetta -LRB- Bayer Leverkusen -RRB- , Valon Behrami -LRB- Lazio -RRB- , Ricardo Cabanas -LRB- Grasshopper -RRB- , Gelson Fernandes -LRB- Manchester City -RRB- , Daniel Gygax -LRB- Metz -RRB- , Benjamin Huggel -LRB- Basel -RRB- , Gokhan Inler -LRB- Udinese -RRB- , Johan Vonlanthen -LRB- Red Bull Salzburg -RRB- . Forwards : Eren Derdiyok -LRB- Basel -RRB- , Alexander Frei -LRB- Borussia Dortmund -RRB- , Marco Streller -LRB- Basel -RRB- , Hakan Yakin -LRB- Young Boys -RRB- .

Turkey :

Goalkeepers : Volkan Demirel -LRB- Fenerbahce -RRB- , Rustu Recber -LRB- Besiktas -RRB- , Tolga Zengin -LRB- Trabzonspor -RRB- . Defenders : Ugur Boral -LRB- Fenerbahce -RRB- , Sabri Sarioglu , Servet Cetin , Hakan Kadir Balta , Emre Gungor -LRB- Galatasaray -RRB- , Gokhan Zan -LRB- Besiktas -RRB- , Emre Asik -LRB- Ankaraspor -RRB- . Midfielders : Mehmet Aurelio , Kazim Kazim -LRB- Fenerbahce -RRB- , Mehmet Topal , Ayhan Akman , Arda Turan -LRB- Galatasaray -RRB- , Emre Belozoglu -LRB- Newcastle -RRB- , Tumer Metin -LRB- Larissa -RRB- , Hamit Altintop -LRB- Bayern Munich -RRB- , Tuncay Sanli -LRB- Middlesbrough -RRB- . Forwards : Gokdeniz Karadeniz -LRB- Rubin Kazan -RRB- , Nihat Kahveci -LRB- Villarreal -RRB- , Semih Senturk -LRB- Fenerbahce -RRB- , Mevlut Erdinc -LRB- Sochaux -RRB- .

@highlight

Group A : Switzerland , Czech Republic , Portugal , Turkey

@highlight

Group B : Austria , Croatia , Germany , Poland

@highlight

Group C : Netherlands , Italy , Romania , France

@highlight

Group D : Greece , Sweden , Spain , Russia